### ISSUE TITLE
Help installing on 20.04

### ISSUE THREAD

**Issue by zilexa** [stewartadam/fwbackups#12]
Just wondering if anyone can help out installing fwbackups on recent Ubuntu (Ubuntu Budgie 20.04.1). 
After installation, I get the error: 
```
/usr/bin/fwbackups: line 30: python: command not found
```
In that file, I changed python > python2.7. Now I get this error when I run `fwbackups`:
```
$ fwbackups
An error occurred while importing gtk/gobject.
Please make sure you have a valid GTK+ Runtime Environment.
```

I also tried: 
```
sudo ln -s ../site-packages/fwbackups /usr/lib/python2.7/dist-packages/fwbackups
```

But that didn't help. 
Your GUI is so straightforward and intuitive, plus as a backup tool for personal files it has all the features I want. I would love to use it as I haven't found a similar easy alternative (and I have been looking a lot).

**Comment by zilexa** [comment]
Never mind, using luckyBackup now.

**Comment by stewartadam** [comment]
Thanks for your interest :)

As fwbackups is in maintenance only mode, it has not received updates to Python 3 neither GTK 3 (and likely won't unless someone wants to PR it). To launch it you'd need Python 2 and PyGTK 2.x, so admittedly another solution is likely a better choice for future-proofing if you had not already been running fwbackups.
