### ISSUE TITLE
meson version error on ubuntu 22.04

### ISSUE THREAD

**Issue by saiballo** [stewartadam/fwbackups#15]
### System Details
- fwbackups version: gtk4
- OS name and version: ubuntu 22.04

### Issue description
when try to build and install I got this error:

The Meson build system
Version: 0.61.2
Source dir: /home/saibal/Scaricati/fwbackups-feature-gtk4
Build dir: /home/saibal/Scaricati/fwbackups-feature-gtk4/_build
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.61.2 but project requires >= 0.62.0

I installed last version of meson in ubuntu 22.04 repository. I will try with flatpak

**Comment by saiballo** [comment]
can't install with flatpak... 

error: org.gnome.Platform/x86_64/43 not installed
Failed to init: Unable to find runtime org.gnome.Platform version 43

But I have installed it

**Comment by stewartadam** [comment]
Hm, I'll see if I can work around the 0.62 features to drop the requirement down a version. In the interim, you can try grabbing the latest version of meson directly from pip:

```sh
pip3 install --user -U meson
which meson
```
It should show `~/.local/bin/meson` (if not, call meson using that path directly).

**Comment by stewartadam** [comment]
Just tested and it looks like the older system meson breaks for installing fwbackups as root, so this should remove meson and install the updated version (system-wide) from pip, then install fwbackups:

```sh
sudo apt remove meson
sudo apt-get install python3-pip
sudo pip3 install meson
meson setup _build -Dpython.install_env=system
meson install -C _build
```

**Comment by stewartadam** [comment]
Let me know if this fixed the issue - If I don't hear back in a few days I'll consider this closed. Thanks!
