### ISSUE TITLE
Broken link to Help

### ISSUE THREAD

**Issue by didier33170** [stewartadam/fwbackups#20]
### System Details
- fwbackups version: 1.43.8-rc2
- OS name and version: Linux Mint 21.1

### Issue description
The links from the application to the online 'help' are broken. They point to the following address : http://downloads.diffingo.com/fwbackups/docs/1.43.8-rc2-html/
Message: '404 Not Found'.

**Comment by stewartadam** [comment]
Thanks for reporting, I've aliased the prior 1.43.7 docs for the 1.43.8rcs until the proper release.
