### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by omniait** [stewartadam/fwbackups#5]
Hello, i get the following error code when trying to launch the application:
```bash
Traceback (most recent call last):

  File "/usr/share/fwbackups/fwbackups-runapp.pyw", line 47, in <module>
    from fwbackups import interface

  File "/usr/lib/python2.7/dist-packages/fwbackups/interface.py", line 23, in <module>
    import gtk.glade
ImportError: No module named glade
```

**Comment by stewartadam** [comment]
Please make sure GTK2 and (its glade module) are installed from your OS package manager. What OS are you using?

**Comment by omniait** [comment]
I'm using Debian 9 with Gnome as DE.
Some modules from GTK2 are installed (libgtk2.0-0, bin and common) and the python-gtk2 binding.
Glade is installed but not libglade2-0, should I install this?
What modules/packages should I look for?
Thanks

**Comment by omniait** [comment]
My missing modules were: libglade2-0 and python-glade2.
After installing them the program works.
Thank you again

**Comment by Klakurka** [comment]
We're missing the Glade module (Centos 8), and the only repository with that seems to be behind a paywall which we'd be happy to pay for if we knew it would work...

https://centos.pkgs.org/8/getpagespeed-x86_64/glade-3.22.1-1.el8.x86_64.rpm.html

Is this the module that needs to be installed to get fwbackups to run after running into the above error?

**Comment by stewartadam** [comment]
Unfortunately that package provides the Glade binary+library for version 3, not the Python binding for version 2 that fwbackups requires.

I'm not aware of any such packages available for CentOS 8, as the Python binding for glade2 was removed from the PyGTK 2 package. The changelog references bug RHBZ#1622134 but it is not available to the public, so the details why are not known.

**Comment by Klakurka** [comment]
Is there a known list of supported Linux distros?

It would be good to know as it sounds like this may be a more common problem as time goes on.

**Comment by stewartadam** [comment]
I haven't tried recently, but Fedora 32 appears to still have the [package in question](https://fedora.pkgs.org/32/fedora-x86_64/pygtk2-libglade-2.24.0-29.fc32.x86_64.rpm.html), as does [CentOS 7 in EPEL](https://centos.pkgs.org/7/centos-x86_64/pygtk2-libglade-2.24.0-9.el7.x86_64.rpm.html).
