### ISSUE TITLE
The preference "start fwbackups when I log in" breaks autostart when there is no folder named autostart

### ISSUE THREAD

**Issue by hcbd** [stewartadam/fwbackups#7]
### System Details
- fwbackups version: 1.43.7
- OS name and version: Fedora 29 + gnome 3.30.2 fresh install

### Issue description
When setting the preference "Start fwbackups (minimized) when I login" to enabled and there is no folder named ~/.config/autostart, fwbackups creates a file names autostart with the fwbackups.desktop contents in it.

### Bug details
Steps to Reproduce:

1. remove or rename: /home/username/.config/autostart
2. open fwbackups and open preferences
3. enable Startfwbackups (minimized) when I login
4. your ~/.config/ folder now has a file named autostart

Observed results:
~/.config/autostart is a file with the contents of the .desktop file (and Gnome-tweaks/gnome-tweak-tool crashes because of it. bugreport: https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/186)

Expected results:
A folder named ~/.config/autostart with the fwbackups.desktop file in it. 

Workaround:
create a folder named autostart in ~/.config/ if there is none

**Comment by stewartadam** [comment]
Closing as 1.43.8 has removed auto-start functionality.
